%%
clear all
close all

load('yb_4_5_snap_bioradiodata.mat')
TrainFeature1 = [BioRadioData{1,4}{1,1},BioRadioData{1,4}{1,2},BioRadioData{1,4}{1,3}];
for ch = 1:3
TrainFeature(:,ch) = [BioRadioData{1,4}{1,ch}(26:50);BioRadioData{1,4}{1,ch}(76:100);BioRadioData{1,4}{1,ch}(126:150);BioRadioData{1,4}{1,ch}(176:200);...
    BioRadioData{1,4}{1,ch}(226:250);BioRadioData{1,4}{1,ch}(276:300);BioRadioData{1,4}{1,ch}(326:350);];
end
CLASS(1:25) = 1;
CLASS(26:50) = 2;
CLASS(51:75) = 3;
CLASS(76:100) = 4;
CLASS(101:125) = 5;
CLASS(126:150) = 6;
CLASS(151:175) = 7;
% subspaceDimension = max(1, min(5, size(TrainFeature,2) - 1));
% classificationEnsembleMatthew = fitensemble(...
%     TrainFeature, ...
%     CLASS, ...
%     'Subspace', ...
%     30, ...
%     'Discriminant', ...
%     'Type', 'Classification', ...
%     'NPredToSample', subspaceDimension, ...
%     'ClassNames', [1; 2; 3; 4; 5; 6;7]);
template = templateSVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    TrainFeature, ...
    CLASS, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', [1; 2; 3; 4; 5; 6; 7]);

 partitionedModel = crossval(classificationSVM, 'KFold', 5);
% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError')
Accuracy(1) = validationAccuracy;
% Compute validation predictions and scores
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);
 C = confusionmat(CLASS,validationPredictions)
 cMatLDA2(1,:,:) = C;
 ClassificationLearner = table([TrainFeature(:,1),TrainFeature(:,2),TrainFeature(:,3)],CLASS');
 %%
 
 labels={'Hand Open','Hand Close','3','4','5','6','7'};
ActualTotalNumber =  sum(squeeze(sum(cMatLDA2,1)),2);
SqueezedcMatLDA2 = squeeze(sum(cMatLDA2,1));
for z = 1:7
    cMatLDAPercent(z,:) = (SqueezedcMatLDA2(z,:)./(ActualTotalNumber(z)))*100;
end

heatmap(cMatLDAPercent, labels, labels, '%0.2f%%','Colormap','jet','ShowAllTicks',0,'UseLogColorMap',true,'Colorbar',true,'ColorLevels',30,'MaxColorValue',100,'MinColorValue',0);
xlabel('Predicted'),ylabel('Actual'),title('Confusion Matrix for One Eye')
xtickangle(60)